services:
  tradesnap:
    image: tradesnap:v0.2.2
    container_name: tradesnap
    env_file:
      - .env
    volumes:
      - ./target/chrome_profile:/app/target/chrome_profile
    networks:
      - cycle
    restart: unless-stopped

networks:
  cycle:
    external: true
